### ISSUE TITLE
initial_config.ini for control modules outdated

### ISSUE THREAD

**Issue by geezIIT** [robotology-playground/GYM#5]
As far as I can tell the initial_config.ini file for the control modules skeleton is outdated. If I understand correctly, $WALKMAN_ROOT should now be replaced by new $ROBOTOLOGY_ROOT env variable.

Example from my newly created module 'athletic':
```
wesley@wesley-Lenovo-B590:~/robotology-superbuild/robots/athletic/build$ cat athletic_initial_config.ini 
# period of the control thread in [millisec]
thread_period 5
# name of the robot
robot_name bigman
# urdf path
urdf_path $WALKMAN_ROOT/drc/iit-bigman-ros-pkg/bigman_urdf/urdf/bigman.urdf
#srdf path
srdf_path $WALKMAN_ROOT/drc/iit-bigman-ros-pkg/bigman_srdf/srdf/bigman.srdf
```

@liesrock Can you confirm this?

**Comment by liesrock** [comment]
Hi Wes,
yes, you are right.
I will create another config file for the robotology and set it as default.

I solved this problem related to multiple config file for different superbuilds (walkman - robotology) and I am going to send and email about this later.

**Comment by liesrock** [comment]
Solved in 88bd2be99c7284e0378e842acc8128d0506db70b

**Comment by geezIIT** [comment]
Shouldn't `~/robotology-superbuild/external/GYM/skeleton/control/app/conf/initial_config.ini` also be updated? Or am I magically receiving another version since I run the non-open superbuild?

**Comment by liesrock** [comment]
Hello geez,
I keep the initial_config.ini for back compatibility with the walkman superbuild.
In the next commit I will solve the problem related with multiple superbuilds.
