### ISSUE TITLE
Add the possibility to "auto-stop" the control thread

### ISSUE THREAD

**Issue by EnricoMingo** [robotology-playground/GYM#7]
Could be useful to have a function in the control thread that permits to stop itself.

**Comment by barbalberto** [comment]
Since control_thread inherits from RateThread you should be able to call ```askToStop()``` from inside the thread itself, if I'm not wrong.

**Comment by liesrock** [comment]
Yes this is right, but we want the Module (who spawns the control thread)  to control the lifecycle of the control thread, not the thread itself.

**Comment by liesrock** [comment]
I was thinking of solving this sending the "stop" command from the control thread to the switch port of the Module.

**Comment by liesrock** [comment]
DEPRECATED repo.
