### ISSUE TITLE
add the paramsTuner to every GYM Module

### ISSUE THREAD

**Issue by arocchi** [robotology-playground/GYM#9]
`paramsTuner.py` was a script, plus executable used to automatically generate UIs for modules using the paramHelper. We should provide a way to tune parameters using a UI:
Either:
- using dynamic reconfigure, or
- using paramsTuner
  What do you think? @liesrock @EnricoMingo 
  I would go for `paramsTuner` since it is already bound with the paramHelper and should be fairly trivial (a couple of hours of work) to integrate automatically with GYM modules.

ps: at the moment the UI is generated using wxWidgets, but in the future it could be rewritten to be built procedurally, for example using http://www.pyqtgraph.org/documentation/parametertree/parametertree.html .. it should be trivial

**Comment by liesrock** [comment]
DEPRECATED repo
